var glyph_sequence = [
{"name":"[unknown]","glyph":{"0":{"2":true,"4":true},"2":{"9":true},"4":{"9":true}}},
{"name":"[unknown]","glyph":{"0":{"2":true,"3":true},"2":{"9":true},"3":{"4":true,"5":true},"4":{"5":true},"8":{"10":true},"9":{"10":true}}},
{"name":"[unknown]","glyph":{"0":{"3":true,"5":true},"3":{"4":true},"5":{"10":true},"7":{"10":true}}},
{"name":"[unknown]","glyph":{"0":{"3":true,"4":true},"3":{"6":true},"4":{"7":true},"6":{"8":true},"7":{"9":true},"8":{"10":true},"9":{"10":true}}},
{"name":"Abandon","glyph":{"2":{"4":true},"4":{"5":true},"5":{"6":true},"6":{"8":true},"8":{"10":true}}},
{"name":"Adapt","glyph":{"1":{"6":true},"5":{"6":true,"7":true}}},
{"name":"Advance","glyph":{"0":{"3":true},"3":{"8":true}}},
{"name":"Again / Repeat","glyph":{"3":{"6":true,"8":true},"4":{"5":true,"7":true},"5":{"6":true}}},
{"name":"All","glyph":{"0":{"1":true,"2":true},"1":{"8":true},"2":{"9":true},"8":{"10":true},"9":{"10":true}}},
{"name":"Answer","glyph":{"3":{"4":true},"4":{"7":true},"5":{"7":true}}},
{"name":"Attack / War","glyph":{"0":{"3":true,"4":true},"3":{"8":true},"4":{"9":true}}},
{"name":"Avoid / Struggle","glyph":{"0":{"1":true,"4":true},"2":{"4":true,"7":true}}},
{"name":"Barrier / Obstacle","glyph":{"0":{"5":true},"5":{"7":true},"7":{"9":true}}},
{"name":"Begin","glyph":{"0":{"6":true},"6":{"10":true},"7":{"10":true}}},
{"name":"Being / Human","glyph":{"3":{"4":true,"6":true},"4":{"7":true},"6":{"10":true},"7":{"10":true}}},
{"name":"Body / Shell","glyph":{"3":{"4":true,"5":true},"4":{"5":true}}},
{"name":"Breathe","glyph":{"1":{"3":true},"2":{"4":true},"3":{"5":true},"4":{"5":true}}},
{"name":"Calibration Grid","glyph":{}},
{"name":"Capture","glyph":{"2":{"7":true},"5":{"6":true,"7":true},"6":{"8":true},"8":{"10":true}}},
{"name":"Change / Modify","glyph":{"5":{"6":true,"10":true},"7":{"10":true}}},
{"name":"Chaos / Disorder","glyph":{"0":{"1":true,"2":true},"1":{"8":true},"2":{"4":true},"4":{"5":true},"5":{"6":true},"6":{"10":true}}},
{"name":"Clear","glyph":{"0":{"5":true},"5":{"10":true}}},
{"name":"Close All","glyph":{"0":{"1":true,"2":true,"5":true},"1":{"8":true},"2":{"9":true},"5":{"10":true},"8":{"10":true},"9":{"10":true}}},
{"name":"Complex","glyph":{"3":{"4":true,"5":true},"5":{"6":true}}},
{"name":"Conflict","glyph":{"3":{"6":true,"8":true},"4":{"7":true,"9":true},"6":{"7":true}}},
{"name":"Contemplate","glyph":{"0":{"2":true},"2":{"9":true},"3":{"5":true,"6":true},"4":{"5":true},"6":{"10":true},"9":{"10":true}}},
{"name":"Contract","glyph":{"4":{"7":true,"9":true}}},
{"name":"Courage","glyph":{"3":{"6":true,"8":true},"6":{"7":true}}},
{"name":"Create / Creation","glyph":{"2":{"4":true},"4":{"5":true},"5":{"6":true},"6":{"8":true}}},
{"name":"Creativity / Mind / Thought / Idea","glyph":{"1":{"3":true,"8":true},"2":{"4":true,"9":true},"3":{"5":true},"5":{"7":true},"6":{"8":true},"7":{"9":true}}},
{"name":"Danger","glyph":{"0":{"3":true},"3":{"5":true},"5":{"10":true}}},
{"name":"Data / Signal / Message","glyph":{"0":{"4":true},"4":{"5":true},"5":{"6":true},"6":{"10":true}}},
{"name":"Defend","glyph":{"1":{"6":true},"2":{"7":true},"6":{"10":true},"7":{"10":true}}},
{"name":"Destiny","glyph":{"3":{"5":true},"4":{"5":true,"7":true},"6":{"7":true,"10":true}}},
{"name":"Destroy / Destruction","glyph":{"1":{"3":true},"3":{"5":true},"5":{"7":true},"7":{"9":true}}},
{"name":"Deteriorate / Erode","glyph":{"3":{"5":true},"5":{"6":true},"6":{"8":true}}},
{"name":"Die","glyph":{"5":{"6":true,"7":true},"6":{"8":true},"7":{"9":true}}},
{"name":"Difficult","glyph":{"2":{"4":true},"4":{"7":true},"5":{"6":true,"7":true}}},
{"name":"Discover","glyph":{"2":{"9":true},"8":{"10":true},"9":{"10":true}}},
{"name":"Distance / Outside","glyph":{"0":{"1":true},"1":{"8":true}}},
{"name":"Easy","glyph":{"4":{"5":true},"5":{"6":true},"6":{"10":true}}},
{"name":"End / Close","glyph":{"0":{"2":true,"5":true},"2":{"7":true},"5":{"10":true},"7":{"10":true}}},
{"name":"Enlightened","glyph":{"0":{"2":true,"3":true},"2":{"9":true},"3":{"4":true,"5":true},"4":{"5":true},"9":{"10":true}}},
{"name":"Equal","glyph":{"3":{"4":true,"6":true},"4":{"7":true}}},
{"name":"Escape","glyph":{"0":{"2":true},"2":{"4":true},"3":{"4":true,"6":true}}},
{"name":"Evolution / Success","glyph":{"0":{"5":true},"3":{"5":true,"6":true}}},
{"name":"Failure","glyph":{"0":{"5":true},"4":{"5":true,"7":true}}},
{"name":"Fear","glyph":{"2":{"7":true},"3":{"4":true},"4":{"7":true}}},
{"name":"Follow","glyph":{"0":{"4":true},"2":{"4":true,"9":true}}},
{"name":"Future / Forward-Time","glyph":{"2":{"4":true},"4":{"7":true},"7":{"9":true}}},
{"name":"Gain","glyph":{"1":{"6":true}}},
{"name":"Government / City / Civilization / Structure","glyph":{"1":{"3":true},"2":{"4":true},"3":{"6":true},"4":{"7":true},"6":{"7":true}}},
{"name":"Harm","glyph":{"0":{"3":true,"4":true},"3":{"5":true},"4":{"5":true},"5":{"7":true},"7":{"9":true}}},
{"name":"Harmony / Peace","glyph":{"0":{"3":true,"4":true},"3":{"5":true},"4":{"5":true},"5":{"6":true,"7":true},"6":{"10":true},"7":{"10":true}}},
{"name":"Have","glyph":{"5":{"6":true,"7":true},"6":{"10":true}}},
{"name":"Help","glyph":{"1":{"3":true},"3":{"5":true},"5":{"6":true},"6":{"7":true}}},
{"name":"Hide","glyph":{"2":{"4":true,"7":true},"3":{"4":true},"6":{"7":true}}},
{"name":"I / Me / Self","glyph":{"3":{"4":true,"10":true},"4":{"10":true}}},
{"name":"Ignore","glyph":{"7":{"9":true}}},
{"name":"Imperfect","glyph":{"3":{"5":true,"6":true},"4":{"5":true},"5":{"6":true}}},
{"name":"Improve","glyph":{"2":{"4":true},"4":{"5":true},"5":{"7":true}}},
{"name":"Impure","glyph":{"3":{"5":true,"6":true},"5":{"6":true,"10":true}}},
{"name":"Journey","glyph":{"1":{"3":true,"8":true},"2":{"4":true},"3":{"5":true},"4":{"5":true},"8":{"10":true}}},
{"name":"Knowledge","glyph":{"3":{"5":true,"10":true},"4":{"5":true,"10":true}}},
{"name":"Lead","glyph":{"0":{"1":true},"1":{"8":true},"6":{"8":true,"10":true}}},
{"name":"Less","glyph":{"3":{"5":true},"4":{"5":true}}},
{"name":"Liberate","glyph":{"0":{"2":true},"2":{"4":true},"3":{"5":true,"8":true},"4":{"5":true}}},
{"name":"Lie","glyph":{"3":{"5":true,"6":true},"4":{"5":true,"7":true},"5":{"7":true}}},
{"name":"Lose","glyph":{"2":{"7":true}}},
{"name":"Message","glyph":{"2":{"7":true},"3":{"5":true,"8":true},"5":{"7":true}}},
{"name":"Mind / Idea / Thought","glyph":{"3":{"5":true,"6":true},"5":{"10":true},"6":{"10":true}}},
{"name":"More","glyph":{"5":{"6":true,"7":true}}},
{"name":"Nature","glyph":{"3":{"4":true,"6":true},"4":{"7":true},"6":{"8":true},"7":{"9":true}}},
{"name":"New","glyph":{"4":{"7":true},"7":{"9":true}}},
{"name":"No / Not / Absent / Inside","glyph":{"3":{"4":true},"4":{"7":true}}},
{"name":"Nourish","glyph":{"5":{"6":true,"10":true},"6":{"8":true},"8":{"10":true}}},
{"name":"Old","glyph":{"1":{"3":true},"3":{"6":true}}},
{"name":"Open / Accept","glyph":{"6":{"7":true,"10":true},"7":{"10":true}}},
{"name":"Open All","glyph":{"0":{"1":true,"2":true},"1":{"8":true},"2":{"9":true},"6":{"7":true,"10":true},"7":{"10":true},"8":{"10":true},"9":{"10":true}}},
{"name":"Opening / Doorway / Portal","glyph":{"1":{"3":true,"8":true},"2":{"4":true,"9":true},"3":{"4":true},"6":{"7":true,"8":true},"7":{"9":true}}},
{"name":"Path","glyph":{"0":{"5":true},"5":{"6":true},"6":{"8":true}}},
{"name":"Perfection / Balance","glyph":{"0":{"5":true},"5":{"6":true,"7":true},"6":{"8":true},"7":{"9":true},"8":{"10":true},"9":{"10":true}}},
{"name":"Potential","glyph":{"0":{"5":true},"2":{"9":true},"5":{"7":true},"7":{"9":true}}},
{"name":"Present / Now","glyph":{"3":{"6":true},"4":{"7":true},"6":{"7":true}}},
{"name":"Pure / Purity","glyph":{"0":{"5":true},"4":{"5":true,"7":true},"5":{"7":true}}},
{"name":"Pursue","glyph":{"0":{"3":true,"4":true},"1":{"3":true}}},
{"name":"Pursue / Chase","glyph":{"0":{"5":true},"3":{"5":true,"6":true},"6":{"8":true}}},
{"name":"Question","glyph":{"0":{"4":true},"3":{"4":true,"6":true}}},
{"name":"React","glyph":{"3":{"4":true,"5":true},"5":{"7":true},"7":{"9":true}}},
{"name":"Rebel","glyph":{"1":{"6":true},"2":{"4":true,"9":true},"4":{"5":true},"5":{"6":true}}},
{"name":"Recharge","glyph":{"0":{"1":true,"5":true},"1":{"3":true},"3":{"5":true}}},
{"name":"Resist / Resistance / Struggle","glyph":{"0":{"3":true,"5":true},"3":{"4":true},"5":{"10":true},"6":{"10":true}}},
{"name":"Restraint","glyph":{"1":{"3":true},"3":{"5":true},"5":{"7":true},"7":{"9":true},"9":{"10":true}}},
{"name":"Retreat","glyph":{"0":{"4":true},"4":{"9":true}}},
{"name":"Safety","glyph":{"3":{"4":true,"8":true},"4":{"9":true}}},
{"name":"Save / Rescue","glyph":{"2":{"7":true},"5":{"6":true,"7":true}}},
{"name":"See","glyph":{"0":{"3":true}}},
{"name":"Seek / Search","glyph":{"3":{"4":true,"6":true},"4":{"5":true},"6":{"7":true}}},
{"name":"Share","glyph":{"6":{"7":true,"8":true},"7":{"9":true},"8":{"10":true}}},
{"name":"Simple","glyph":{"6":{"7":true}}},
{"name":"Soul / Spirit / Life Force","glyph":{"4":{"5":true,"7":true},"5":{"10":true},"7":{"10":true}}},
{"name":"Stability","glyph":{"6":{"7":true,"8":true},"7":{"9":true}}},
{"name":"Strong","glyph":{"3":{"4":true,"6":true},"4":{"7":true},"6":{"7":true}}},
{"name":"Together","glyph":{"3":{"4":true,"5":true},"4":{"5":true},"5":{"6":true},"6":{"8":true}}},
{"name":"Truth","glyph":{"3":{"5":true,"6":true},"4":{"5":true,"7":true},"5":{"6":true,"7":true}}},
{"name":"Use","glyph":{"2":{"7":true},"5":{"7":true}}},
{"name":"Victory","glyph":{"0":{"3":true,"4":true},"3":{"10":true},"4":{"10":true}}},
{"name":"Want","glyph":{"6":{"8":true,"10":true},"7":{"10":true}}},
{"name":"We / Us","glyph":{"3":{"4":true},"4":{"10":true}}},
{"name":"Weak","glyph":{"1":{"3":true},"3":{"4":true},"4":{"7":true}}},
{"name":"XM (Exotic Matter)","glyph":{"3":{"4":true,"6":true},"4":{"7":true},"5":{"6":true,"7":true}}},
{"name":"You / Other","glyph":{"0":{"6":true,"7":true},"6":{"7":true}}},
];
