var glyph_sequence = [
{"name":"Abandon","glyph":{"2":{"4":true},"4":{"5":true},"5":{"6":true},"6":{"8":true},"8":{"10":true}}},
{"name":"Adapt","glyph":{"1":{"6":true},"5":{"6":true,"7":true}}},
{"name":"Advance","glyph":{"0":{"3":true},"3":{"8":true}}},
{"name":"Again / Repeat","glyph":{"3":{"6":true,"8":true},"4":{"5":true,"7":true},"5":{"6":true}}},
{"name":"All","glyph":{"0":{"1":true,"2":true},"1":{"8":true},"2":{"9":true},"8":{"10":true},"9":{"10":true}}},
{"name":"Answer","glyph":{"3":{"4":true},"4":{"7":true},"5":{"7":true}}},
{"name":"Attack / War","glyph":{"0":{"3":true,"4":true},"3":{"8":true},"4":{"9":true}}},
{"name":"Avoid / Struggle","glyph":{"0":{"1":true,"4":true},"2":{"4":true,"9":true}}},
{"name":"Barrier / Obstacle","glyph":{"0":{"5":true},"5":{"7":true},"7":{"9":true}}},
{"name":"Begin","glyph":{"0":{"6":true},"6":{"10":true},"7":{"10":true}}},
{"name":"Being / Human","glyph":{"3":{"4":true,"6":true},"4":{"7":true},"6":{"10":true},"7":{"10":true}}},
{"name":"Body / Shell","glyph":{"3":{"4":true,"5":true},"4":{"5":true}}},
{"name":"Breathe","glyph":{"1":{"3":true},"2":{"4":true},"3":{"5":true},"4":{"5":true}}},
{"name":"Calibration Grid","glyph":{}},
{"name":"Capture","glyph":{"2":{"7":true},"5":{"6":true,"7":true},"6":{"8":true},"8":{"10":true}}},
{"name":"Change / Modify","glyph":{"5":{"6":true,"10":true},"7":{"10":true}}},
{"name":"Chaos / Disorder","glyph":{"0":{"1":true,"2":true},"1":{"8":true},"2":{"4":true},"4":{"5":true},"5":{"6":true},"6":{"10":true}}},
{"name":"Clear","glyph":{"0":{"5":true},"5":{"10":true}}},
{"name":"Close All","glyph":{"0":{"1":true,"2":true,"5":true},"1":{"8":true},"2":{"9":true},"5":{"10":true},"8":{"10":true},"9":{"10":true}}},
{"name":"Complex","glyph":{"3":{"4":true,"5":true},"5":{"6":true}}},
{"name":"Conflict","glyph":{"3":{"6":true,"8":true},"4":{"7":true,"9":true},"6":{"7":true}}},
{"name":"Contemplate","glyph":{"0":{"2":true},"2":{"9":true},"3":{"5":true,"6":true},"4":{"5":true},"6":{"10":true},"9":{"10":true}}},
{"name":"Contract","glyph":{"4":{"7":true,"9":true}}},
{"name":"Courage","glyph":{"3":{"6":true,"8":true},"6":{"7":true}}},
{"name":"Create / Creation","glyph":{"2":{"4":true},"4":{"5":true},"5":{"6":true},"6":{"8":true}}},
{"name":"Creativity / Mind / Thought / Idea","glyph":{"1":{"3":true,"8":true},"2":{"4":true,"9":true},"3":{"5":true},"5":{"7":true},"6":{"8":true},"7":{"9":true}}},
{"name":"Danger","glyph":{"0":{"3":true},"3":{"5":true},"5":{"10":true}}},
{"name":"Data / Signal / Message","glyph":{"0":{"4":true},"4":{"5":true},"5":{"6":true},"6":{"10":true}}},
{"name":"Defend","glyph":{"1":{"6":true},"2":{"7":true},"6":{"10":true},"7":{"10":true}}},
{"name":"Destiny","glyph":{"3":{"5":true},"4":{"5":true,"7":true},"6":{"7":true,"10":true}}},
{"name":"Destroy / Destruction","glyph":{"1":{"3":true},"3":{"5":true},"5":{"7":true},"7":{"9":true}}},
{"name":"Deteriorate / Erode","glyph":{"3":{"5":true},"5":{"6":true},"6":{"8":true}}},
{"name":"Die","glyph":{"5":{"6":true,"7":true},"6":{"8":true},"7":{"9":true}}},
{"name":"Difficult","glyph":{"2":{"4":true},"4":{"7":true},"5":{"6":true,"7":true}}},
{"name":"Discover","glyph":{"2":{"9":true},"8":{"10":true},"9":{"10":true}}},
{"name":"Distance / Outside","glyph":{"0":{"1":true},"1":{"8":true}}},
{"name":"Easy","glyph":{"4":{"5":true},"5":{"6":true},"6":{"10":true}}},
{"name":"End / Close","glyph":{"0":{"2":true,"5":true},"2":{"7":true},"5":{"10":true},"7":{"10":true}}},
{"name":"Enlightened","glyph":{"0":{"2":true,"3":true},"2":{"9":true},"3":{"4":true,"5":true},"4":{"5":true},"9":{"10":true}}},
{"name":"Equal","glyph":{"3":{"4":true,"6":true},"4":{"7":true}}},
{"name":"Escape","glyph":{"0":{"2":true},"2":{"4":true},"3":{"4":true,"6":true}}},
{"name":"Evolution / Success","glyph":{"0":{"5":true},"3":{"5":true,"6":true}}},
{"name":"Failure","glyph":{"0":{"5":true},"4":{"5":true,"7":true}}},
{"name":"Fear","glyph":{"2":{"7":true},"3":{"4":true},"4":{"7":true}}},
];